### ISSUE TITLE
Document data quality issues

### ISSUE THREAD

**Issue by gwaybio** [WayScience/CFReT_data#3]
We have noticed some relatively minor (and common) issues with data quality in this dataset.

Some issues include blurriness, debris, and high levels of channel bleed-through. 

@jenna-tomkinson - please make sure to make detailed notes of these issues. These notes likely belong in the `preprocessing` module alongside IC (and elsewhere TBD)!

**Comment by jenna-tomkinson** [comment]
@gwaybio I agree! I am working on the document (spreadsheet) that will document the images and the issues within them (e.g yes for blurriness, no for smudging, etc.).

I would say the preprocessing module is the best place.

I do wonder if there is a way that we can make a function to take in the spreadsheet, and where there is a file that has a yes to any issues, have it removed. This would make it easier to remove images for this larger data set instead of doing it manually. 

I will investigate the latter after completing the document.

**Comment by jenna-tomkinson** [comment]
@gwaybio 

We decided to use a module within CellProfiler called `MeasureImageQuality` to give us blur metrics that are included within the `.sqlite` file outputted during feature extraction.

This will allow us to assess images that are considered blurry based on the metrics and if there is any impact on the morphological readouts.

**Comment by jenna-tomkinson** [comment]
I have done some analysis using this method, so I believe this issue has been resolved. I will be closing it now.
